import { person, sections } from './content';
import { safeUrl } from './model';
const escape = (value: string) => value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]!));
export function textPage(): string {
  const portfolio = sections.filter(section => section.id !== 'extras');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${escape(person.name)} - ${escape(person.title)}"><title>${escape(person.name)} | Text Portfolio</title><style>
  *{box-sizing:border-box}html{color-scheme:light;scroll-behavior:auto}body{margin:0;background:#f5f6f3;color:#24332b;font:17px/1.7 Arial,Helvetica,sans-serif;letter-spacing:0}main{max-width:800px;margin:auto;padding:42px 28px 80px}a{color:#275c49;text-underline-offset:4px;overflow-wrap:anywhere}a:focus-visible{outline:3px solid #275c49;outline-offset:5px}h1{font-size:42px;line-height:1.2;margin:36px 0 8px;font-weight:500}h2{font-size:26px;margin:0 0 25px}h3{font-size:19px;line-height:1.5;margin:30px 0 12px}p{margin:12px 0}header p{color:#5b675b}nav{display:flex;gap:8px 22px;flex-wrap:wrap;padding:26px 0}nav a{min-height:44px;display:flex;align-items:center;font-size:14px}section{border-top:1px solid #cbd3c8;margin-top:28px;padding-top:30px}article{margin-bottom:32px}small{font-size:13px;color:#596858}.back{display:inline-flex;align-items:center;min-height:44px;font-size:14px}.tools{font-size:14px;color:#4d5f50}footer{margin-top:50px;font-size:13px}li{margin-bottom:12px}button{font:inherit} @media(max-width:420px){main{padding:24px 22px 60px}h1{font-size:34px}}@media print{.back,nav{display:none}body{background:white;font-size:11pt}main{padding:0}h1{font-size:28pt}article{break-inside:avoid}h2,h3{break-after:avoid}}
  </style></head><body><main><a class="back" href="./index.html">&#8592; Return to the phone</a><header><h1>${escape(person.name)}</h1><p>${escape(person.title)}<br>${escape(person.location)}</p></header><nav aria-label="Portfolio sections">${portfolio.map(s => `<a href="#${s.id}">${escape(s.title)}</a>`).join('')}</nav>${portfolio.map(s => `<section id="${s.id}" aria-labelledby="title-${s.id}"><h2 id="title-${s.id}">${escape(s.title)}</h2>${s.entries.map(e => `<article><h3>${escape(e.title)}</h3>${e.paragraphs.map(p => `<p>${escape(p)}</p>`).join('')}${e.topics?.filter(t => t.title === 'Repository').map(t => `<p>${escape(t.paragraphs.join(' '))}</p>`).join('') ?? ''}${e.tools ? `<p class="tools"><strong>Tools:</strong> ${escape(e.tools.join(', '))}</p>` : ''}${safeUrl(e.url) ? `<p><a href="${escape(safeUrl(e.url)!)}" target="_blank" rel="noopener noreferrer">${e.topics ? 'View repository' : `Open ${escape(e.shortTitle)}`} (new tab)</a></p>` : ''}</article>`).join('')}</section>`).join('')}
  <section id="credits"><h2>Credits &amp; Sources</h2><p>An independent portfolio, not affiliated with or endorsed by Nokia. Nokia is a trademark of its respective owner.</p><h3>Handset Photograph</h3><p><a href="https://commons.wikimedia.org/wiki/File:Nokia_3310_Blue_R7309170_(retouch).png">Nokia 3310 Blue R7309170 (retouch)</a> by Rainer Knäpper (smial), retouched by Multicherry, used under the <a href="https://artlibre.org/licence/lal/en/">Free Art License 1.3</a>. Resized and converted to WebP, with a replacement LCD and interactive control overlays. The adapted handset visual is available under the same license. <a href="./assets/nokia-3310.webp" download>Download the adapted image</a>.</p><p>Pixel glyphs and synthesized key tone are original work. Lucide icons use the ISC license. No original Nokia ringtone or proprietary font is redistributed.</p><h3>Hardware References</h3><ul><li><a href="https://www.mobilephonemuseum.com/phone-detail/nokia-3310">Mobile Phone Museum: Nokia 3310</a> (2000 launch and model identification).</li><li><a href="https://www.gsmarena.com/nokia_3310-192.php">GSMArena: Nokia 3310</a> (113 x 48 x 22 mm; 133 g).</li><li><a href="https://www.techradar.com/news/phone-and-communications/mobile-phones/nokia-s-3310-the-greatest-phone-of-all-time-1287636">TechRadar: Nokia 3310 retrospective</a> (84 x 48 monochrome display).</li><li><a href="https://nokia-3310.helpdoc.net/en/1-your-phone/using-the-keys/navi-key/">Nokia manual transcription: Navi key</a> (one contextual action button).</li><li><a href="https://commons.wikimedia.org/wiki/File:Nokia_3310_grey_all_sides.jpg">Multicherry: all-sides reference</a> (CC BY-SA 4.0; reference only, not redistributed).</li></ul><p>References accessed 6 September 2026. Photographic perspective, regional key legends, and a slightly expanded LCD viewport are retained or adapted for usability. The rendered body is not a calibrated engineering model.</p><h3>Content &amp; Privacy</h3><p>Professional information comes exclusively from the supplied resume. Personal email and phone number are excluded. The original resume is not distributed. Project repositories were verified against the owner's public GitHub profile. Project dates, named roles, public demos, and certificate verification links were not supplied. Work experience and unsupported awards are omitted.</p></section><footer>Arunesh Waran &middot; AI, ML &amp; Web Application Developer</footer></main></body></html>`;
}
